---
docker_port:
  -
    host: 2376
    guest: 2376
container_ports:
  -
    host: 4000
    guest: 4000
shares:
  -
    host:
      isRelative: 1
      path: ../moveme_pipeline-output
    guest:
      path: /pipeline-output
  -
    host:
      isRelative: 1
      path: ../moveme_curated-data
    guest:
      path: /curated-data
