FROM sirile/minijavabox
MAINTAINER jefeweisen@users.noreply.github.com

# JVM code:
ADD dockerpipeline.jar /var/lib/dockerpipeline.jar

# ExternalProcess scripts, etc:
ADD dockerpipeline /lib/dockerpipeline
